cds-snc/ircc-rescheduler

- .env.local
- .eslintrc.js
- package.json
- src/__tests__/After.test.js
- src/__tests__/HomePage.test.js
- src/server.js
- test/server.test.js
- test/setupTests.js
- yarn.lock
This commit replaces razzle test with calling jest directly.
This means that all the config razzle generates for jest needed to be
replicated, and saved in the package.json.
Currently the installed version of jest is locked in at 20.0.4 to match
the one that Razzle uses. Without this we get "TypeError:
environment.setup is not a function".
> Get basic Jest testing setup.

- .babelrc
- package.json
- src/client.js
- yarn.lock
As advertised. Tested in Browserstack. Closes #9.
> ie11 support via babel-preset-env

- src/CalendarPage.js
- src/ConfirmationPage.js
- src/FourOhFourPage.js
- src/HomePage.js
- src/Layout.js
- src/forms/__tests__/MultipleChoice.test.js
- src/forms/__tests__/TextInput.test.js
- src/styles.js
Our pages all have common headers and footers, so some kind of Layout abstraction will help us maintain that consistency.
Also helps us move some of that global CSS, which means that we can move away from creating a ton of global styling on the Home page.
**Note**
I didn't put this is as a post-it note earlier today because I forgot about it. But I had been working on this since Friday (ie, I was already halfway through it), so I figured I should push on.
> Create Layout component, reorder some CSS 

- .circleci/config.yml
Back to how it used to be when we had green checkmarks. 
If the branch is called `add-deploy`, it will run through the whole deploy process for us so we don't have to merge this change to master to see how it will turn out.
> Revert CircleCi config

- web/src/Document.js
- web/src/client.css
- web/src/client.js
Removed client.css file as well as the import within client.js
body {
margin: 0;
padding: 0;
font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen,
Ubuntu, Cantarell, 'Open Sans', 'Helvetica Neue', sans-serif;
}
After our css resets, I'm pretty sure this wasn't doing anything
> Page Titles + Removed client.css

- web/src/RegistrationPage.js
- web/src/ReviewPage.js
- web/src/Summary.js
- web/src/forms/MultipleChoice.js
- web/test/server.test.js
Noticed a few little problems while demoing the app.
- radio inputs didn't have a white background
- some of the radio CSS was a bit mangled from a merge conflict or something
- colons for all form headings on review page
- "go back" on review page wasn't returning to the calendar
> Clean up some words and radio styling

- web/src/client.js
- web/src/utils/createApolloClient.js
-issue stems from the server side rendering of the application being desynched from the client side. Issue stemmed from the createApolloClient function using a fat arrow syntax, not sure why that mattered. 
-Also added a comment as a reminder that any SSR warnings will be easier to debug if the two statements proceeding the comment get removed.
> Fix the console warning that would occur in development

- web/src/CalendarPage.js
- web/src/FederalBanner.js
- web/src/Footer.js
- web/src/LanguageSwitcher.js
- web/src/RegistrationPage.js
- web/src/styles.js
This pull request does a few little things.
1. Adds hidden `<h1>`s to registration and calendar page so that a screenreader will tell you what the point of the page is. Resolves #80.
2. Changes some `<section>`s into `<div>`s. Addresses some of the concerns in #78.
3. Adds a tabindex and some keypress stuff to the language switcher. You wouldn't be able to find/use it with a keyboard otherwise.
> Add hidden page titles to describe registration and calendar pages

- web/src/Calendar.js
- web/src/CalendarPage.js
- web/src/RegistrationPage.js
- web/src/_Field.js
- web/src/__tests__/Calendar.test.js
- web/src/forms/MultipleChoice.js
- web/src/forms/TextInput.js
- web/src/forms/__tests__/MultipleChoice.test.js
- web/src/forms/__tests__/TextInput.test.js
This pull request:
- Adds calendar validation
- Navigates to the review page if 3 or more dates are selected
- Shows an error if less than 3 dates are selected
- integrates our `Calendar` with `react-final-form`, so that we can use `onSubmit` to get the calendar values
- adds @zakkain's error message from #79 
- adds some basic unit tests for the `Calendar`
- resolves #52, although more work needs to be done on saving dates and making it a nice interaction
- allow dates to be pre-populated in the rendered calendar
This pull request does not:
- save dates to state (so they can be queried on the review page, for example)
- ~create a `CalendarAdaptor` component to separate our `Calendar` from `react-final-form`~
- I don't think I want to do this anymore, actually.
- add unit tests for …
> Add calendar validation logic

- Makefile
- dev.yml
- web/razzle.config.js
Start the app in development mode with `make dev`.
If jest is installed globally you can also run `make test`.
Minor change to web service to get webpack-dev-server listening on all ports
rather than just locally so that it works in a container.
You will notice that port 3005 is mapped directly to the host rather than going
through the proxy like 3004. This is a workaround for fact that I couldn't
figure out how to get Traefik to properly route to both 3004 & 3005. I will
fight that battle again another day.
Also note the environmental variables that are expected to exist.
> Add makefile with docker-compose dev file

- web/src/Calendar.js
- web/src/CalendarPage.js
- web/src/LinkStateDisplay.js
- web/src/ReviewPage.js
- web/src/Summary.js
- web/src/Time.js
- web/src/__tests__/Calendar.test.js
- web/src/__tests__/Time.test.js
- web/src/queries.js
- web/src/utils/createApolloClient.js
This pull request:
- Saves dates (as date strings) to the cache
- Displays saved dates on the `/review` page 
- resolves #88 
- Creates a `Time` component that returns an [HTML `<time>` element](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/time) 
- partially addresses, but does not resolve, #86
- Adds some date parsing utility methods
- Returns selected dates to the calendar when the user clicks 'Go back →' from the review page
- Adds tests around returning dates and then clicking new ones
> Save calendar dates

- web/src/__tests__/FederalBanner.test.js
- web/src/__tests__/Footer.test.js
- web/src/__tests__/PageHeader.js
- web/src/forms/__tests__/Button.test.js
- web/src/forms/__tests__/MultipleChoice.test.js
- web/src/forms/__tests__/TextInput.test.js
The way we were writing these tests, they would always return true.
Now we are explicitly looking for how many elements we expect.
Also rewrote one of our footer tests so that it's no longer comparing itself to itself.
> Update `toBeTruthy` unit tests

- web/src/FederalBanner.js
- web/src/Footer.js
- web/src/forms/TextInput.js
Between Firefox and IE, we were getting a few CSS inconsistencies.
| ie11 | firefox |
|------|---------|
|  ![image](https://user-images.githubusercontent.com/2454380/39776907-22e99326-52d0-11e8-9ef7-de7828b28c4f.png)    |   <img width="1221" alt="screen shot 2018-05-08 at 2 55 58 pm" src="https://user-images.githubusercontent.com/2454380/39776996-5159bcfe-52d0-11e8-8f92-0f173a2664e1.png"> |
**Solution**
Fixed sizes for svgs. We don't really change their size anyway.
| ie11 | firefox |
|------|---------|
|  ![image](https://user-images.githubusercontent.com/2454380/39777097-a353e03e-52d0-11e8-9939-101e493393e3.png)  |  ![image](https://user-images.githubusercontent.com/2454380/39777159-cc40bfa8-52d0-11e8-875f-6c7da0d59317.png) |
**Solution**
Explicit font-family rules for text inputs and …
> Fix SVG size, make fonts for text-based input elements sans-serif

- api/package.json
- api/src/messages.js
- api/src/schema.js
- api/src/types/RescheduleForm.js
- api/test/api.test.js
- api/yarn.lock
- web/src/ReviewPage.js
- web/src/queries.js
This commit adds:
* availability to the RescheduleForm input type
* Validation that availability is a proper date
* Validation that 3 dates are the only acceptable number of dates
* updated query in the web service to include dates
> Submit dates along with other user data

- api/package.json
By default, Jest helpfully creates a document object to help testing of UI
components. For a strictly node.js project like the api, that work is unneeded and
can be skipped to save some time. This change reduces the time to run the test
suite from 1.437s to 0.834s.
> Avoid JSDOM test environment for the API

- web/locale/_build/src/LandingPage.json
- web/locale/_build/src/Layout.json
- web/locale/_build/src/ReviewPage.json
- web/locale/_build/src/__tests__/Summary.json
- web/locale/en/messages.json
- web/locale/fr/messages.json
As advertised. Just `yarn extract --clean` to remove the kruft.
> Remove obsolete translations

- web/src/AlphaBanner.js
- web/src/FederalBanner.js
- web/src/LandingPage.js
- web/src/Layout.js
- web/src/PageHeader.js
- web/src/styles.js
- web/test/server.test.js
This PR is a start towards the beta redesign that we're doing:
- Adds pink alpha colour to `AlphaBanner` (same as on [the CDS products page](https://digital.canada.ca/products/))
- Adds Federal Identity red flag
- `PageHeader` background changes to Canada.ca blue (also shorter)
- `PageHeader` no longer uses an `<h1>`, which is great because now we don't have two `<h1>`s on every page
- Copy on landing page gets a revamp
- words have been updated and visually it just looks nicer
There is more to do as part of the reskinning but this is a good start.
| before | after | mockup |
|--------|-------|--------|
| <img alt="screen shot 2018-05-15 at 9 10 06 am" src="https://user-images.githubusercontent.com/2454380/40058801-3edc4a56-5820-11e8-9936-3f958b223ee7.png"> | <img  alt="screen shot …
> Redesign landing page for beta

- web/src/CalendarPage.js
- web/src/LandingPage.js
- web/src/RegistrationPage.js
- web/src/forms/Button.js
- web/src/styles.js
This pull request:
- Styles our buttons so that they look more like [GOV.UK buttons](https://govuk-elements.herokuapp.com/buttons/)
- Also exports the button styles so that we can use them on other elements that aren't buttons (ie, links for example [like on the landing page])
- Finally, the link on our landing page is just a link now and not a link wrapping a button (this is great)
- Adds `system-ui` as an explicit font declaration so that link buttons look identical to regular buttons
- Removes unicode arrows except on the first and last pages of our little service 
| before | after | mockup |
|--------|-------|--------|
| <img alt="screen shot 2018-05-15 at 10 58 15 am" src="https://user-images.githubusercontent.com/2454380/40065175-1d8a7288-582f-11e8-8054-f961ed364cb9.png"> |  <img …
> Make buttons look more like GOV.UK buttons

- web/src/components/Submission.js
- web/src/components/__tests__/Submission.test.js
Previously, our `Submission` component was catching GraphQL errors, like an email being sent with the wrong fields, but wasn't catching regular Errors, like a NetworkError.
Now it catches both.
> Catch errors more comprehensively

- web/src/components/ErrorMessage.js
- web/src/components/Layout.js
- web/src/styles.js
Just a few small quality-of-life changes in this PR:
- some CSS changes to keep all page content at 80% width on larger screens
- using a less harsh red for our error messages
- add `role="banner"` to all of our headers
- this was because the `aXe` auditing tool was complaining about it
Very minor visual changes.
> Spit and polish

- web/src/components/Calendar.js
- web/src/components/__tests__/Calendar.test.js
- web/src/pages/CalendarPage.js
- web/src/styles.js
- web/test/server.test.js
This pull request does a bunch of fun stuff:
- Updates the calendar styling
- Calendar now shows one month at a time
- Calendar now has hover/focus styles so that it's keyboard navigable
- Calendar looks a bit nicer
- Updates the list of dates beside the calendar
- When no dates are selected, users see three grey boxes
- As users select dates, they are entered into the boxes and a "remove" button appears
- Updates the words on the calendar page to match the mock-up
- Simplifies some of the internal date storage
Merging this pull request resolves #86.
**Note: the code is all there so you can build locally, but I can't upload screenshots right now**
|  two-month calendar no dates selected   |   one-month calendar no dates selected |
|   <img …
> Clean up calendar

- web/locale/_build/src/components/Calendar.json
- web/locale/_build/src/components/Layout.json
- web/locale/_build/src/pages/CalendarPage.json
- web/locale/_build/src/pages/ErrorPage.json
- web/locale/_build/src/pages/LandingPage.json
- web/locale/_build/src/pages/RegistrationPage.json
- web/locale/_build/src/pages/ReviewPage.json
- web/locale/en/messages.json
- web/locale/fr/messages.json
- web/package.json
- web/src/client.js
- web/src/components/Layout.js
- web/src/pages/ErrorPage.js
- web/src/pages/__tests__/ErrorPage.test.js
- web/src/server.js
- web/yarn.lock
This commit adds error tracking. It uses a new ErrorBoundary component from
gcui to catch errors occuring in the coponent tree and display an error state.
Sentry is used to log the error with an optional form for capturing user
feedback.
The ErrorPage has been changed slightly to be a little friendlier and more generic:
Clicking the link brings up Sentry's user feedback form:
> Add error tracking with Sentry

- web/package.json
- web/yarn.lock
This is a bandaid more than anything.
When we run `yarn upgrade razzle`, our hot reloading is breaking. It might be to do with emotion, but I'm not sure.
Short term: I've upgraded all the other packages but reverted the razzle-specific ones. 
Long term: We upgrade razzle. Either it is fixed by itself (unlikely), we fix hot-reloading, or we lose hot-reloads.
> Revert yarn.lock to fix hot reloading

- package.json
should make this slightly easier to work with 
- just run `yarn start` instead of stopping and starting
- added build steps for both api/web
> improvements to run scripts

- web/.gitignore
- web/package.json
- web/src/components/Layout.js
- web/src/utils/analytics.js
- web/yarn.lock
Adds Google Analytics to every page using the [`react-ga`](https://github.com/react-ga/react-ga) library.
Added some logic to make sure that Google Analytics is only started when
- the `NODE_ENV` environment variable is set to 'production'
- the `RAZZLE_GA_ID` environment variable exists (this should be our Google tracking ID)
Otherwise, the app will run as normal and nothing will be logged.
Currently there is a print statement each time a page is logged by Google Analytics. We should shut this off before we are in live beta or whatever, but for now this seems okay.
Merging this resolves (long-standing) issue #8.
//
This is the same library that the VAC team are using, so we can help each other if need be.
Relevant VAC pull request:
cds-snc/vac-benefits-directory#42
Also this example was …
> Add Google Analytics to track pageviews

- web/src/components/Calendar.js
- web/src/components/__tests__/Calendar.test.js
Up to now, dates would show up in the order the user selected them.
ie, if they selected "June 8, June 5, June 1", they would be displayed in that order.
This could lead to the assumption that their preferred ordering was important when making their selection.
Since we're not letting them order dates at all, we're enforcing a chronological order which is how IRCC will get them.
now, if they select
-  "June 8, June 5, June 1"
they will see
- "June 1, June 5, June 8" 
as the dates they have selected.
Test it out here (might take a while to load but just grit your teeth): https://ircc-rescheduler-pyizkhsyuf.now.sh/calendar
Merging this PR resolves issue #129
> Order list of selected days chronologically

- web/src/components/Footer.js
- web/src/styles.js
|    ![41063620-26eda6cc-69a7-11e8-9e2b-f991575f1376](https://user-images.githubusercontent.com/30609058/41242796-770eb554-6d6e-11e8-9b77-0f4f5735829a.jpg)    |   <img width="387" alt="screen shot 2018-06-11 at 11 59 19" src="https://user-images.githubusercontent.com/30609058/41242955-faba8176-6d6e-11e8-9ce3-a2648567d41f.png">  |
**For Mobile:**
- Reduced the size of the Canada Wordmark by 50%
- Removed row-reverse as the flex-direction so that the footer is ordered Wordmark -> Links
- Font-size reduction on smaller screens for the links
- 'Terms and Conditions' becomes 'Terms' on smaller screens
**For Desktop:**
- Removed row-reverse as the flex-direction so that the footer is ordered Wordmark -> Links
> Footer restyling

- web/src/components/Layout.js
- web/src/components/PageHeader.js
- web/src/pages/ConfirmationPage.js
- web/src/pages/ErrorPage.js
- web/src/pages/FourOhFourPage.js
- Creating a visuallyHiddenOnMobile class in styles.js
- Reducing the font-size on PageHeader.js while on a mobile device
|  ![screen shot 2018-06-12 at 12 51 40](https://user-images.githubusercontent.com/30609058/41304897-626b1ea4-6e3f-11e8-896f-0f441716b110.png)   | ![screen shot 2018-06-12 at 12 43 51](https://user-images.githubusercontent.com/30609058/41304809-2b0747ee-6e3f-11e8-8de2-07156e9997fc.png)|
- Hiding the PageHeader.js on mobile devices for the Confirmation, Error and 404 pages 
|  ![screen shot 2018-06-12 at 12 45 32](https://user-images.githubusercontent.com/30609058/41304986-8aa8a198-6e3f-11e8-82f7-95751c31e898.png) | ![screen shot 2018-06-12 at 12 44 …
> Make page title "Request to Reschedule...." smaller, visuallyHiddenOnMobile

- web/src/components/AlphaBanner.js
- Adjusting alpha banner mobile functionality to display the banner message beside the badge instead of below it.
|    ![alphabannerbefore](https://user-images.githubusercontent.com/30609058/41320798-35fba67e-6e6f-11e8-88ec-bc7d88cbd73b.gif)    |   ![alphabannerafter](https://user-images.githubusercontent.com/30609058/41320797-35e9411e-6e6f-11e8-945c-1cf61bd7f06e.gif)    |
> Alpha Banner Alignment

- web/src/pages/ConfirmationPage.js
- web/src/pages/LandingPage.js
- web/src/pages/RegistrationPage.js
**Landing Page**
- Remove “full name” item
- Six (6) weeks -> Nine (9) weeks
**Info Page**
- Change “Reason for rescheduling” to “Why are you rescheduling?” And remove text below
**Confirmation**
- Under “Thank you! Your request was received.” add “We’ve sent you a confirmation email.”
- Change “6 weeks” to “July 6, 2018" (edited)
> Usability Content changes discluding cal changes

- web/src/components/Calendar.js
- web/src/components/__tests__/Calendar.test.js
- web/src/pages/CalendarPage.js
This PR changes our calendar date range to be more realistic for tomorrow's usability testing.
It also introduces the concept of allowing weeks as well as just months.
Before we had all weeks in June and July.
Now we have 
- the last 3 weeks of July
- August
- the first 2 weeks of September
|  June → July  | July → September       |
|    ![dates-0](https://user-images.githubusercontent.com/2454380/41364703-682b4438-6f05-11e8-8953-c889152c3a3e.gif)    |   ![dates-1](https://user-images.githubusercontent.com/2454380/41364712-6e206fee-6f05-11e8-96c0-cc1afb099f72.gif)   |
Also updated our hardcoded test dates with new hardcoded test dates. If you want the rationale, pls read 0998f12eab034fa17ccafd7805aafc22f03677ca.
> Speed dating 📅

- web/src/components/Layout.js
- web/src/styles.js
The Internet Explorers of the world have problems with the HTML5 `<main>` tag, so I just kept the main as an unstyled markup element and changed Content to a `div`.
Means our site displays properly again in IE11.
This PR resolves #158.
More on `<main>`s for those interested: https://www.w3.org/TR/wai-aria-practices/examples/landmarks/main.html
> Remove styling from `<main>` element

- web/src/components/FederalBanner.js
- web/src/components/LanguageSwitcher.js
This pull request makes the language link smaller on mobile and keeps it on the same line as the Canadian Identity stuff. It also reduces the vertical padding a bit and makes the FIP banner smaller on really <sup>tiny</sup> screens.
When going through the page with a screenreader, the link will always be read as "français" and never "FR".
|  francais link drops down to next line     | francais link shortened to "RF" and stays on the same line    |
| ![screen shot 2018-06-14 at 4 21 12 pm](https://user-images.githubusercontent.com/2454380/41436235-06997b50-6fef-11e8-8dca-dfb65ab0639f.png) | ![screen shot 2018-06-14 at 4 21 06 pm](https://user-images.githubusercontent.com/2454380/41436252-0e32df8c-6fef-11e8-9b0d-79320d876708.png) |
| …
> Language link is littler

- web/src/components/Summary.js
- web/src/pages/ConfirmationPage.js
- web/src/pages/ErrorPage.js
- web/src/pages/LandingPage.js
- web/src/pages/ReviewPage.js
- web/src/styles.js
- Page header reduced in size:
|   <img width="905" alt="screen shot 2018-06-20 at 17 38 44" src="https://user-images.githubusercontent.com/30609058/41686386-de874d3c-74b1-11e8-9c00-77cba03e07c8.png">     |    <img width="894" alt="screen shot 2018-06-20 at 17 42 34" src="https://user-images.githubusercontent.com/30609058/41686384-dc9f8354-74b1-11e8-9e33-31e346ef3ef5.png">   |
- Summary header margin increase:
|   <img width="917" alt="screen shot 2018-06-20 at 17 39 01" src="https://user-images.githubusercontent.com/30609058/41686412-fc270bca-74b1-11e8-80f1-53af161d9647.png">  | <img width="890" alt="screen shot 2018-06-20 at 17 42 49" …
> Amend Review + Confirmation Pages + Error

- web/src/components/ErrorMessage.js
- web/src/components/__tests__/ErrorMessage.test.js
- web/src/pages/LandingPage.js
- web/src/pages/RegistrationPage.js
- web/src/pages/ReviewPage.js
- web/test/server.test.js
This PR updates copy in the error message block on the form page. 
This PR updates the language around rescheduling and the impact on current appointments:
> Copyediting Pass: Form Page Error Block & Toughened Rescheduling Language

- api/src/types/RescheduleForm.js
- web/src/components/LinkStateDisplay.js
- web/src/components/Summary.js
- web/src/components/__tests__/Summary.test.js
- web/src/pages/ConfirmationPage.js
- web/src/pages/RegistrationPage.js
- web/src/pages/ReviewPage.js
- web/src/queries.js
- web/src/utils/createApolloClient.js
Added an email field to the Registration form. 
Now all emails sent by our app will include the user's inputted email as well as the rest of it (ie, dates, name, reason, etc.).
This story does _not_ yet send an email to the user's provided email. That will be done in an upcoming pull request.
> add email field to reg form

- api/index.js
Our inline-css package wants a URL from us so that it can give us good links to stuff once we render everything to text.
But if we don't need to worry about this (ie, currently we don't have any links in our emails so no problemo), then their advice is to pass in an empty string.
BUT! Passing in an empty string would fail our falsey check in `api/index.js` so now it doesn't.
🎈 🎉 🎈 
Docs:
https://github.com/jonkemp/inline-css#optionsurl
> Tiny config change for the API

- web/package.json
- web/src/components/Layout.js
- web/src/pages/ConfirmationPage.js
- web/yarn.lock
- GCUI was updated as per a PR request done by me (we are now getting the role and aria-label attributes showing up)
- Changed the Rescheduler projects version of gcui from ^0.0.29 to ^0.0.30
- Added feedback mechanism to open the google form link in a separate tab:
|   ![screen shot 2018-06-22 at 10 05 03](https://user-images.githubusercontent.com/30609058/41780857-f0060b36-7603-11e8-8244-e38bfc236206.png)|  ![feedback-after](https://user-images.githubusercontent.com/30609058/41780886-00313cec-7604-11e8-9cdb-6b047a73f481.gif)     |
> Feedback mechanism on confirmation page

- web/src/components/forms/MultipleChoice.js
I shrunk the radio buttons down in size for [the NRCan app](http://nrcanpoc.azurewebsites.net/search), and ported them into this one without changing them too much.
We want to keep them at a 40px by 40px hit state so that they are super easy to click on.
|   desktop  |   desktop    |
|    <img width="1247" alt="screen shot 2018-06-22 at 5 33 45 pm" src="https://user-images.githubusercontent.com/2454380/41800302-f42c18d8-7642-11e8-998d-995d2e4fa9cc.png"> |  <img width="1247" alt="screen shot 2018-06-22 at 5 33 49 pm" src="https://user-images.githubusercontent.com/2454380/41800301-f35ad3a4-7642-11e8-91b3-2989e6ef8632.png"> |
|   mobile   |  mobile   |
|  <img width="546" alt="screen shot 2018-06-22 at 5 34 32 pm" …
> Embiggen radio buttons

- web/src/components/Contact.js
- web/src/components/__tests__/Contact.test.js
- web/src/pages/ErrorPage.js
- web/src/pages/__tests__/ErrorPage.test.js
This PR address content changes to the error page. Do not merge until team has reviewed and changes are final (by end of day Tuesday).
Content and ordering is relevant, visual design and spacing **will be changed** with coming global typography updates.
**Before:**
**After:**
> Content changes to the Error page

- web/src/components/Calendar.js
- web/src/components/Time.js
- web/src/components/__tests__/Calendar.test.js
- web/src/components/__tests__/Time.test.js
- web/src/pages/CalendarPage.js
- web/src/pages/CancelPage.js
- web/src/pages/ConfirmationPage.js
- web/src/pages/NoJSCalendarPage.js
- web/src/pages/ReviewPage.js
This PR:
- changes the date range to August 1st - September 20th (ie 4 weeks from July 4th, and then 8 weeks of Wednesdays and Thursdays)
- Updates our date format to display longer months and days
- `Thu, Sep 6, 2018` -> `Thursday, September 6, 2018`
- `jeu. 6 sept. 2018` -> `jeudi 6 septembre 2018`
- updates page copy where we refer to dates
- updates our "Go Back" links to say "Go back"
- updates our hardcoded tests
|    ![calendar-1](https://user-images.githubusercontent.com/2454380/41935246-f8fa3afe-7956-11e8-90c0-a5803350ea6a.gif)    |  ![calendar-2](https://user-images.githubusercontent.com/2454380/41935242-f67f5e30-7956-11e8-9b3c-a1a4d4316782.gif)     |
> Go-live date change 📅

- shipitfile.js
Our email isn't sending properly because we have a linked file in our repo which it can't find once it's deployed.
> Add image to list of shared files

- web/src/__tests__/WithProvider.test.js
- web/src/cookies.js
- web/src/pages/RegistrationPage.js
- web/src/withProvider.js
There's a lot going on here, but, as before, it's been prototyped out at https://github.com/pcraig3/after-no-js. This PR doesn't update our language switcher to actually sent requests to change the language, but you can see this working at [https://nojs.now.sh/](https://nojs.now.sh/).
1. Consolidate cookie validation logic
Both server-side and client-side cookies are put through the same validation logic now, in `WithProvider.validateCookie()`.
Before, the No-JS validation was happening in [`setSSRCookie`](https://github.com/cds-snc/ircc-rescheduler/blob/master/web/src/cookies.js#L59), while the JS validation was happening in the pages themselves. They were similar but now they are the same.
Also added a bunch of tests for it since it's very easy to throw things at it and see what comes …
> Consolidate cookie validation logic + add `language` to store

- web/src/components/PhaseBanner.js
For visited links it will already be white, but it was showing up as blue for people who hadn't clicked it before.
> White feedback link in header

- .gitignore
- web/.env
- web/.env.local
- web/src/cookies.js
@damcom-gc mentioned today that some of our web header stuff wasn't locked down.
One of the not-locked-down things we're doing is setting browser cookies which are returned over both HTTP and HTTPS. If we set `secure: true` (ie, in [res.cookie](https://expressjs.com/en/4x/api.html#res.cookie)), they will only be returned over HTTPS (which means they're encrypted over the wire). 
I've done some `.env` changes here to accommodate for this, because locally we are running on `http://localhost:3004` and we need to be able to get cookies back.
As a developer on this project, you should create a `.env.local` file which will make sure cookies are always served over HTTP for local development.
```
RAZZLE_COOKIE_HTTP=true
```
> Set secure cookies 🔐 🍪

- api/src/schema.js
- api/test/i18n.test.js
- web/package.json
- web/src/server.js
- web/src/utils/createApolloClient.js
A couple changes in here:
- created a new object from `res.body` so that we're not mutating it
- added paperFileNumber to test data
- removed 'test' mutation since we no longer need it
- redirect to `/confirmation` if no error is thrown
- added an absolute URL in production since that seems to be an issue
> Make a GraphQL post from the server II

- web/src/components/CalendarNoJS.js
- web/src/components/forms/MultipleChoice.js
- web/src/pages/CalendarPage.js
- web/src/pages/RegistrationPage.js
This PR does a couple things:
- removes some unused CSS from the checkboxes + radios styling
- cleans up a linting error we were getting by not passing an array to `oneOfType`
- adds some dummy input elements to our registration page and No-JS calendar page
- not my proudest moment (more info below)
***
|  radio hidden on the registration page   |  radio unhidden!    |
|     <img width="957" alt="screen shot 2018-06-29 at 9 18 35 pm" src="https://user-images.githubusercontent.com/2454380/42120066-e46f0c98-7be2-11e8-92a8-15bc44ba8ca4.png">   |    <img width="957" alt="screen shot 2018-06-29 at 9 18 37 pm" src="https://user-images.githubusercontent.com/2454380/42120067-e554d0ac-7be2-11e8-8cab-d4f416a04527.png">   |
|  small checkboxes + first one is …
> Merge 1st: Reveal radios + checkboxes

- web/src/components/Calendar.js
- web/src/components/CalendarNoJS.js
- web/src/components/Time.js
- web/src/components/__tests__/Calendar.test.js
- web/src/components/forms/MultipleChoice.js
- web/src/pages/CalendarPage.js
- web/src/pages/RegistrationPage.js
- web/src/pages/ReviewPage.js
**Note: this PR follows up on #219, which should be merged first.**
_This PR is only from commit 3ce8e9293724be5ac0d06e4257edbefb5968adb6 onwards._
***
This PR: 
- fixes the error message on the No-JS calendar page so that it only shows up when it's meant to
- changes `calendar.calendar` → `calendar.selectedDays` everywhere
- saves values from both calendars in the same format
- does some styling updates to the No-JS calendar
- reuses `ErrorList` -- I know there's only one possible error to link to but it seemed better to link than to not
- adds the more descriptive aria-label to the `Remove day` button
- this is one of the issues noted in https://github.com/cds-snc/ircc-rescheduler/issues/161
Things we could do in the future:
- use `date-fns` stuff in `Time` 
- revisit the displayed …
> Merge 2nd: Polish up No-JS calendar + save dates the same way between calendars

- api/src/email.js
- api/src/email_templates/applicant-plain.html
- api/src/email_templates/applicant-rich.html
- api/src/schema.js
- api/test/email.test.js
- web/src/components/__tests__/Calendar.test.js
Our as-of-right-now confirmation email is pretty skimpy: just a name and a list of dates.
The updated content makes for a much better email.
We say hello, we show the dates, we give them contact information, and we have all the content in both english and french.
This PR resolves #225.
<sup>(note, the large black bar in the screenshot is an anomaly. both black bars are the same size) </sup>
*
> Better confirmation email for users 

- web/src/components/__tests__/Calendar.test.js
- web/src/utils/calendarDates.js
This update uses the utility methods in calendarDates matching the Calendar output against dynamic data (start / end dates etc...).
> Refactor Calendar Tests to use non-hardcoded data

- web/src/components/Footer.js
- web/src/components/LanguageSwitcher.js
- web/src/components/PageHeader.js
- web/src/components/Reminder.js
- web/src/components/__tests__/Footer.test.js
- web/src/components/__tests__/LanguageSwitcher.test.js
- web/src/components/__tests__/PageHeader.test.js
- web/src/components/__tests__/Reminder.test.js
So the essence of this ticket is that @pcraig3 fixed the issue of needing a translate method for when we need a string at runtime since the ```i18n``` object was null at times. So I can now just use ```i18n_()``` to get a translated string at runtime and this also means that ```yarn extract && yarn compile``` will generate the string in the designated json files.
> Fix some of the lingui translations we had for strings

- web/src/components/LanguageSwitcher.js
- web/src/components/Layout.js
- web/src/components/PageHeader.js
- web/src/components/__tests__/PageHeader.test.js
- I am blocked on the sentry stuff until tomorrow because I am not an admin.
- And I'm blocked on the noJS date stuff until Dave is back.
So I ran an axe audit over our site and noticed a couple low-hanging fruit I could go after. Was planning to do this before next week's audit so this seems like a good a time as any.
A couple of small changes, just.
- the FederalBanner should be within a landmark region
- in this case, I moved it into the div with the "header" role
- having a <header> element within a <div role="header"> is bad, so
I changed to PageHeader to just be a <div> and updated its test.
This takes us from 5 issues on most pages to 2 issues (the colour
contrast of the beta tag).
Similarly to how the Français link in the language switcher
becomes "FR" on small devices, the …
> Fix some axe violations + get language switcher to say "English / EN"

- web/src/components/Contact.js
- web/src/components/__tests__/Contact.test.js
Without the `mailto:` prefix in the href, we are just sending people to a 404 page if they click the email link on the confirmation page.
> Fix email link

- .gitignore
- package.json
- shipitfile.js
- web/.env
- web/.gitignore
- web/package.json
- web/src/__tests__/Validation.tests.js
- web/src/components/ErrorMessage.js
- web/src/pages/CalendarPage.js
- web/src/pages/RegistrationPage.js
- web/src/validation.js
- web/yarn.lock
As per #238 this adds a new level of validation to the project.
Code has been setup to roughly drop / replace the existing validation.
validatorjs has been added which allows rules to be defined as simple objects
```
let rules = {
name: 'required',
email: 'required|email',
age: 'min:18'
};
```
Error messages can be customized for single elements which is what we're doing.
Typically that would be done as follows:
```
{
'required.fullName': 'some message',
'max.fullName': 'another message'
}
```
In our case given our translation setup the messages has been setup to be used as message keys
```
{
'required.fullName': 'fullNameErrorMessage',
}
```
An error messages object has been setup to handle the translations 
```
export const errorMessages = {}
errorMessages.fullNameErrorMessage = ( …
```
> Better Field Validation

- web/src/client.js
We were not using the CDS corporate Sentry account, but now we are.
NOT IN THIS PR:
- stop sending errors in dev mode !!!
- send formatted errors that make sense
But for now, this is just somewhere where everyone on the team can see it.
> Move to corporate CDS sentry account

- web/.gitignore
- web/package.json
- web/razzle.config.js
- web/yarn.lock
Added the bundle analyzer for our razzle-webpack config. This will allow us to see just how much resource each library and js file takes up. 
-Currently spits out a stats json and a report.html file in the ircc/web/build folder. 
-This can be run using ```yarn stats```
-You can even try running this on the production build by changing the ```stats``` command to use ```start``` instead of ```dev```, they give slightly different results. 
-This is only for the web folder, not sure about adding it to the api folder given our deployment strategy is changing, but it shouldn't be the most difficult thing to add in the future. 
-the bundle analyzer has different config options in of itself, can configure it to host a server instance instead of a static html report (which shows a bit more …
> Add bundle analyzer 

- ecosystem.config.js
- package.json
This should fix the issue with starting node with the full-icu path - which loads translations for date formats - by calling `npm start` which passes in that argument.
> get pm2 to start the services using our package.json scripts

- web/package.json
- web/razzle.config.js
-Last bundle analyzer PR had some issues with it, the prod command didn't work without yarn build. and one report was generated in the right place and the other one wasn't. So in this PR I am only adding one command to the package.json file instead of previously two, so we should only need to see the prod version of the bundle. This is also way cleaner since this means a server doesn't need to run to generate the reports.
> Fix up the bundle anayzer to generate two different files in the same directory

- web/locale/en/messages.json
- web/locale/fr/messages.json
- web/src/pages/RegistrationPage.js
Trello: https://trello.com/c/ncgirHyW/234-fix-accuracy-of-the-paper-file-number-helper-text-on-the-form-page-xs 
This PR updates the descriptive text for the "Paper file number" field for accuracy.
English: `This number is at the top of the email attachment we sent you.`
French: `Il s'agit du numéro qui est affiché en haut du email pièce jointe que nous vous avons envoyé.`
Merge only once translation is confirmed (cc @anikbrazeau) ✅ **Translation confirmed**
> Fix accuracy of the Paper File Number helper text on the form page

- web/package.json
- web/src/components/Calendar.js
- web/yarn.lock
- yarn.lock
- Adds aria-level attribute to the Calendar Month Name
- Upgraded react-day-picker to the latest version ``` "react-day-picker": "^7.1.10" ```
> Add aria-level to month name

- web/src/styles.js
@emanelfy noticed that our "send request →" and "cancel request" button text would break across lines for some screen sizes. 
Did some CSS changes so that the line breaks earlier. There are other ways to solve this (fixed widths, non-breaking spaces, etc), but this seemed easy enough. Tested on the french version of the review page since that one has the largest amount of button text.
|  words break across lines 👎    |  words never break across lines 👍   |
| ![buttons-2](https://user-images.githubusercontent.com/2454380/42887188-5afede58-8a73-11e8-92fd-418ec96c7ccd.gif) |  ![buttons](https://user-images.githubusercontent.com/2454380/42887167-4e94c22c-8a73-11e8-85c7-dc1f3d8b5b2a.gif)  |
> Bottom button text never breaks across lines

- web/src/components/PhaseBanner.js
|    <img width="601" alt="screen shot 2018-07-18 at 13 59 06" src="https://user-images.githubusercontent.com/30609058/42899008-c58662fe-8a92-11e8-91f3-83121d348e52.png"> |   <img width="594" alt="screen shot 2018-07-18 at 13 58 00" src="https://user-images.githubusercontent.com/30609058/42899009-c59a049e-8a92-11e8-9a44-5da7ef909e0e.png">   |
- The old color was failing AA and AAA accessibility standards
- The new color meets both AA and AAA accessibility standards
> Beta Colour Contrast 

- web/src/components/Calendar.js
Updates aria-label for calendar day cell to be consistent with date formatting used throughout the app.  Also handles translation.
Keep existing functionality for Day cell untouched.
> Calendar day date aria-label

- web/package.json
- web/src/server.js
- web/yarn.lock
- Previously errors we're logged in the console without notice of failure being reported back (outside of redirecting to an error page)
- Added the Node version of Raven and a call to capture the exception
- Moving forward we should move the Raven credentials into an .env file so we can re-use in multiple spots.
The easiest way I have found to test so far is to adjust the Params in the server code to use a null sending address
```
const applicantOptions = {
htmlTemplate: 'applicant-rich',
plainTemplate: 'applicant-plain',
...
sendingAddress:null,
}
```
> Adds Sentry error logging for failed AWS emails

- web/src/client.js
- web/src/pages/ErrorPage.js
To run sentry locally now, you're going to have to run `yarn start`
Notes:
- could have also set the DSN string to empty, as per this comment
https://github.com/getsentry/raven-js/issues/105#issuecomment-340215644
but not installing at all seems cleaner
> Only install sentry in production mode

- web/package.json
- web/razzle.config.js
- web/src/server.js
- web/yarn.lock
Use the sentry webpack plugin to update our artifacts in sentry with the proper sourcemaps.
Notes to keep in mind:
-Running this requires an api key with ```project:write selected under scopes.``` under the sentry ui when you generate one. 
https://docs.sentry.io/clients/javascript/sourcemaps/
-The api key is an environment variable
> Add sourcemaps for sentry logging

- web/src/components/Calendar.js
- web/src/components/__tests__/Calendar.test.js
- web/src/utils/__tests__/calendarDates.test.js
- web/src/utils/calendarDates.js
This update checks to see if the saved values contain selected days.  If selected days exist we will use the first value as the default for initial month for the calendar.
Note: I set a couple of calendar tests to be skipped.   The calendar tests need to be updated to handle the amount of days in the current view based on either the default start month or a passed in value for selected days.  The existing solution counting the days for the current month view isn't a good solution.  We should do something based on the available dates array.  This logic needs to be updated across most of the calendar tests so I don't want to create a temp solution to get the tests passing again.  Needs to be thought out and more forward thinking.
> Use inputed value as selected month

- web/src/components/__tests__/Calendar.test.js
Update calendar tests to use valid days arrays for tests
This updates adds a new function to seek out a month to use for the tests that has at least 3 valid dates.
The tests have been fragile as we have been relying either upon the inital view to have multiple dates available or simulating clicks on the view to get to a month where we have enough dates.  This was falling out of sync with the dates trying to be selected.
> Update calendar tests to use valid days arrays for tests

- web/src/cookies.js
Since values are being saved for a week, but our calendar updates every day, you can get into a state where:
- you select the first available dates
- you come back nearly a week later and you have dates selected that are greyed-out on the calendar
Shortening cookies to 1 day will resolve the bulk of these problems for us.
> Shorten cookie expiration to a day

- web/src/components/Calendar.js
- web/src/components/Chevron.js
- web/src/components/Layout.js
- web/src/components/__tests__/Calendar.test.js
- hides chevrons from screenreaders (explicitly, so that accessibility tests are happy)
- fixes layout bug in Safari and IE11
- sets default link colour (before we were relying on browser defaults)
- removes alt-text from "remove day" `imgs` since the ANDI accessibility scan is flagging that as a potential issue
| ![screen shot 2018-07-30 at 2 21 42 pm](https://user-images.githubusercontent.com/2454380/43416251-c30383be-9405-11e8-890e-f00fc698f341.png)  | ![screen shot 2018-07-30 at 2 21 55 pm](https://user-images.githubusercontent.com/2454380/43416252-c406edc8-9405-11e8-9ad9-3ed8e09b7746.png) |
| before | after | after after |
|--------|-------|-------------|
| <img width="847" alt="screen shot 2018-07-30 at 2 46 08 pm" …
> Hide chevrons from screenreaders

- web/src/components/__tests__/PhaseBanner.test.js
Stops printing out the console.error message in the console, but it _does_ test that the right error message is being logged.
The tests still pass as they did before, they're just a bit nicer now.
|  ![test-1](https://user-images.githubusercontent.com/2454380/43426817-1497068c-9425-11e8-8277-9356df6a701e.gif)  | ![test-2](https://user-images.githubusercontent.com/2454380/43426816-14895410-9425-11e8-8bcb-af169235c472.gif) |
> Clean up PhaseBanner test

- web/src/pages/ReviewPage.js
This fixes the sort order of the dates on the Review Page. 
Previously this page would display dates in the order that the user selected the dates.
**Note:**
Ultimately it would be nice to have a single function to handle this for all the possible output (Calendar, Review Page + Email).  Maybe updating sortSelectedDays to check if the items in the array are dates already.  Would need to determine what each page / component is looking for.
> Update review days to show sorted dates selected

- web/src/components/Calendar.js
- web/src/pages/CalendarPage.js
This update fixes the issue where the calendar error for max three days was one click behind if you had already submitted the form and we're seeing the you must select 3 days warning.
As noted here https://github.com/cds-snc/ircc-rescheduler/pull/283#issuecomment-407166015
> Calendar Max 3 days error.

- web/email_templates/applicant-plain.html
- web/email_templates/applicant-rich.html
Trello card: https://trello.com/c/sO78JfXh/255-rewrite-ambiguous-contact-language-in-the-confirmation-email-and-confirmation-page-etc
This PR addresses an issue discovered in testing: that some users are reading the "Contact" language in the email as a direction, not a resource if they need it. 
New copy fixes that (French has been updated as well, as the changes duplicate existing content)
> Rewrite ambiguous "Contact" language in the confirmation email

- web/src/__tests__/WithProvider.test.js
- web/src/withProvider.js
If someone explicitly sets a default language, or passes in a "language" query parameter, we save that to a cookie.
However, when they come to our site for the first time:
- they won't have any cookies
- they probably aren't passing in a query param
- they may have a language setting in their browser
So that's the case we want to check.
If there are no cookies and their "Accept-Language" header (comes through as lowercase in express) starts with either "en", or "fr", then we'll pick a default language for them.
Note that it is possible someone will have a header like:
- `"es,en-US,en"`
- `"zh, fr-CA, en"`
In both of those cases, the string "fr" or "en" exists in their accept-language header, but it's not being picked up.
Since I doubt that that is happening to us, I am opting for simpler …
> Listen for "accept-language" browser header

- web/src/components/Calendar.js
When returning to the calendar that already has 3 selected days, the calendar does not allow days to be unselected.
I haven't properly debugged the problem but this would revert it back to how it was before https://github.com/cds-snc/ircc-rescheduler/pull/302
> Remove forceRender call until bug is fixed

- web/src/components/LanguageSwitcher.js
- web/src/components/Layout.js
- web/src/utils/analytics.js
Sends Google Analytics event to track when users click the language toggle link.
Adds a label parameter to the logEvent function so we can track value
i.e. logEvent('Navigation', 'Toggle Language', 'FR')
Also added a few checks for window as Razzle was complaining.  Likely a timing issue.
> Track language toggle

- web/src/components/Contact.js
|   <img width="250" alt="screen shot 2018-08-02 at 14 01 08" src="https://user-images.githubusercontent.com/30609058/43601981-a9ea4d50-965c-11e8-9fa6-ad250c204042.png">     |   <img width="244" alt="screen shot 2018-08-02 at 14 01 56" src="https://user-images.githubusercontent.com/30609058/43601980-a9d6ab06-965c-11e8-937e-2622506b5c5b.png">    |
(Merging this PR closes #319 )
> Fixed Wordbreak on confirmation mobile screens

- web/cypress/integration/main/cal-change-unselect.spec.js.js
- web/cypress/integration/main/cal-clear-show-errors.js
- web/src/components/Calendar.js
- web/src/pages/CalendarPage.js
Fixes issue where Calendar errors for too many days selected ends up behind by one click.
The previous fix for this used forced render which fixed the error issue but, created an issue where users could not unselect dates after they we're saved to the cookie.
In this version we're passing the selected stated back to the force render and than updating state (using either the saved or state for the Calendar initial values).
This allows the Calendar to do a full re-render while maintaing the correct dates.
> Calendar Error Regression

- web/src/pages/CalendarPage.js
Correct issue where after the user had saved 3 dates and the data was in the cookie if the user returned to update and removed all the dates the selected dates would re-fill with the saved cookie values.
> Unselect all after save issue

- web/src/pages/RegistrationPage.js
If a user triggered an error message at some point while
entering data, that error message would be saved to local state
and never be reset.
In practice, this meant that users would not be able to save
correct values once the invalid error message had been triggered.
In practice, this was the error:
- if a user entered a bad paper file number and pressed "submit",
they would see a validation message
- once they corrected the mistake, they would progress through
to the review page
- on the review page, they would see that their value was not
saved
- if they clicked "change" they would still not be able to save
a new paper file number
This is bad news, but resetting the error messages solves this issue.
> Reset error messages when a validate passes

- web/cypress/integration/main/review-missing-data.spec.js
- web/src/server.js
When the form is submitted previously we could not tell when a redirect from missing data was happening.  This adds a not-valid=true to the redirect from the server to help surface issues faster in Google Analytics.
Also added end-to-end tests to ensure this functions as expected.
> Add unique url param for form submitted with data missing

- web/README.md
- web/src/utils/__tests__/cleanInput.test.js
- web/src/utils/__tests__/url.tests.js
- web/src/utils/gitHash.js
By setting the returned value to `process.stdout`, it seems like the result of the execSync call was being logged to the screen while the value returned to the app was `000000`.
[The docs say that the default value is 'pipe'](https://nodejs.org/api/child_process.html#child_process_child_process_execsync_command_options), so I've reset the first two std values to 'pipe'
Note: I tried to write tests for this, but ran into two problems
1. I can't predict whether this will be run from a git repo or not, so I don't know what value to expect
2. I couldn't figure out how to get the logged hash from the original function while still in a test
I think it's okay as-is, but open to suggestions.
> gitHash returns hash as variable rather than logging it

- web/cypress/integration/main/cal-clear-show-errors.js
- web/src/components/Calendar.js
- web/src/components/CalendarNoJS.js
- web/src/components/__tests__/Calendar.test.js
- web/src/locations/vancouver.js
- web/src/pages/CalendarPage.js
- web/src/utils/__tests__/calendarDates.test.js
- web/src/utils/calendarDates.js
- web/src/utils/gitHash.js
- web/src/utils/url.js
- web/test/server.test.js
This update moves to an initial location based setup.
Appointment day availability is now based on an object with a recurring property.
Days available are grouped by month.
Example:
```
const vancouver = {
email: 'IRCC.DNCitVANNotification-NotificationVANCitRN.IRCC@cic.gc.ca',
phone: '1-888-242-2100',
recurring: {
jun: ['wed', 'thurs'],
jul: ['wed', 'thurs'],
aug: ['wed', 'thurs'],
sep: ['wed', 'thurs'],
oct: ['tues', 'thurs'],
nov: ['mon', 'fri'],
},
}
```
Calendar day highlighting and Calendar page note about what days appointments can be scheduled on is now also dynamic.
Note: Translations have not been exported yet.
> Modify calendar available dates to be dynamic by month

- web/cypress/fixtures/user.json
- web/cypress/integration/main/validation-error-query-params.spec.js
- web/cypress/integration/main/validation-error.spec.js
We recently had a problem where validation errors would cause values not be saved.
We've since released a fix for this, and these tests are confirming the correct behaviour.
It's not doing a lot of code reuse, so I can do some refactoring if needed.
> Add tests that include tripping validation errors

- web/README.md
- web/package.json
- web/src/cookies.js
- web/src/server.js
- web/yarn.lock
We don't need it.
- Cookies are only served to our rescheduler domain (means that other
sites can't look at them).
- Our rescheduler domain only sends cookies over HTTPS, so the site
traffic is encrypted end-to-end
There shouldn't be a way to actually get the content of the cookies
unless you're the person who entered the values in the first place.
> Remove cookie encryption

- web/cypress/integration/main/cal-clear-show-errors.js
- web/src/pages/CalendarPage.js
- We had fixed this earlier, but now it's showing a blank error message again, so added a test case that submits with no days selected and looks for the error message.
|   ![screen shot 2018-08-13 at 12 13 01](https://user-images.githubusercontent.com/30609058/44045083-7f6e7834-9ef5-11e8-83d3-715bb0c8e65a.png)     |   ![screen shot 2018-08-13 at 12 13 04](https://user-images.githubusercontent.com/30609058/44045084-7f80680a-9ef5-11e8-8c25-68c26443d242.png)    |
- test has been updated to support the no dates selected use case
> Fixed Calendar Bug + Updated Cypress test

- web/src/Document.js
Since now we are loading Raven async, we no longer need to download Raven independently.
Fixes downloading Raven twice 👇
> Remove extra raven download

- web/email_templates/applicant-plain.html
- web/src/components/Contact.js
- web/src/components/Footer.js
- web/src/components/__tests__/Contact.test.js
- web/src/components/__tests__/Footer.test.js
- web/src/email/email-template.js
- web/src/locations/vancouver.js
This updates moves from using hardcoded values for email and phone to use the location file / object.
For now a couple of utility methods (getEmail, getPhone) have been added to that file as well.  Those will get moved out once we determine how we're moving forward with other locations.
> Use location object for email and phone across the app

- web/public/fonts/fonts.css
- web/src/Document.js
- web/src/components/Calendar.js
- web/src/components/ErrorMessage.js
- web/src/components/LanguageSwitcher.js
- web/src/components/Layout.js
- web/src/components/PageHeader.js
- web/src/components/PhaseBanner.js
- web/src/components/Reminder.js
- web/src/components/forms/Button.js
- web/src/pages/CalendarPage.js
- web/src/pages/LandingPage.js
- web/src/pages/RegistrationPage.js
- web/src/styles.js
Unfortunately, when #366 went in, I didn't notice that the fonts were getting loaded twice.
They _are_ getting preloaded, but the `@font-face` declaration in `injectGlobal` doesn't actually use those downloads, and re-downloads the fonts.
So, I took a look at [this example of preloading fonts](https://github.com/zachleat/web-font-loading-recipes/blob/master/preload.html) and implemented it in our app. Now we're a-OK.
The other thing that changed is that I am naming both fonts as the same font family, but giving them different weights. Again, this is what [the example](https://github.com/zachleat/web-font-loading-recipes/blob/master/preload.html) does.
This means that when we want to switch between fonts in our app, all we have to do is switch the `font-weight` value.
This solves a couple …
> Fix our font loading

- web/src/Document.js
For some reason, Chrome will download the preloaded fonts, and then ignore them and re-download them _again_.
Other browsers don't do this -- only Chrome.
If you want to read up on this super weird behaviour:
- https://github.com/w3c/preload/issues/32#issuecomment-196223669
- https://bugs.chromium.org/p/chromium/issues/detail?id=584198
- https://stackoverflow.com/a/36508361/9728185
And there's a good example in the MDN docs:
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/link
> Add crossorigin="anonymous" to preload links so that fonts don't download twice in Chrome

- web/src/server.js
Routing users back to fill in missing data shouldn't happen given a typical user flow.  If we end up flagging missing data and redirecting we should be notified we can look further into potential issues.
This update sends a simple message to Sentry for these case so the information is logged and we will receive an email notification.
**Sample of info showing in Sentry:**
> Add Sentry notification for missing data redirects

- web/src/components/__tests__/Calendar.test.js
This reverts the Calendar tests to bring back some code that was used to ensure that the Calendar tests have enough dates to work with per month view.
These functions got removed during some cleanup work.
> Ensure 3 dates for calendar view

- shipitfile.js
Up to now, we've been installing all production and dev dependencies when deploying the application.
Dev dependencies are used for things like testing or linting, but they aren't needed when running the application. Skipping dev dependencies will make our deployments faster and hopefully get them to actually work again 🤞
> Only install production dependencies when deploying

- web/cypress/integration/main/keep-data-query-params.spec.js
- web/cypress/integration/main/review-missing-data.spec.js
- web/src/__tests__/WithProvider.test.js
- web/src/withProvider.js
Because of the way we are handling query parameters (ie, assuming that they represent data the user os trying to submit), we've ended up in a few cases where user data has been lost based on query parameters that users haven't entered.
This PR will ignore query parameters that don't contain any keys related to values on the page.
Added a new unit test and a new cypress test.
> Only validate query parameters when a query param key matches a field on the page

- web/src/__tests__/WithProvider.test.js
- web/src/pages/__tests__/NoJS.test.js
- web/src/withProvider.js
On the landing page, the pathname is "/".
Since it would be trimmed in the `returnKeyAndValue` function, we would be passing key === '' to `validateCookie`. This meant that [`validateCookie` would error out](https://github.com/cds-snc/ircc-rescheduler/blob/master/web/src/withProvider.js#L176).
In practical terms, this meant that visiting the root URL "/" and passing in a query parameter would cause the language to switch back to English.
The fix for this is to never return an empty string as a key from `returnKeyAndValue`.
- added unit test
- added puppeteer test which reloads the home page several times and checks the language setting is preserved
> Keep language query consistent on Landing Page

- web/package.json
- web/src/components/FederalBanner.js
- web/yarn.lock
In our last round of accessbility testing, there was a bug uncovered where IE11 would automatically focus on our Canadian Federal logo (ie, an svg), even though this is a non-interactive element and does not have a focus indicator.
Fix is to add a `focusable="false"` attribute to the svg.
- https://github.com/PolymerElements/iron-iconset-svg/issues/46
Went into GCUI to make the change, and added tests for it in there.
- https://github.com/cds-snc/gcui
Tested this fix using Browserstack and it behaves as expected.
---
Note: was planning to do some experimenting on cutting down the GCUI bundle size, but now that we have a rollout in a couple weeks, I'm putting that one on the back-burner.
> Prevent IE11 from focusing on Canada government logo

- web/jest-no-js.config.js
- web/jest.config.js
- web/package.json
Since adding the puppeteer tests, our `yarn test` command would fail when running without building and starting the app first.
By ignoring the NoJS.test.js file, we can run the rest of our jest tests from the command line without the faff of spinning the app up and down.
This deceptively simple problem turned out to be a bit more complicated than just doing a regex or passing a new command line argument.
In the end, I created a dedicated `jest.config.js` file that jest will use on CI test runs, and a second config file that ignores the NoJS tests so that we can run the other ones locally. Using the spread operator to reuse nearly the same config options between both files.
File matching using regex is also still working as before. ie, if I just wanted to run calendar-related tests, I can …
> Ignore Puppeteer tests in `yarn test`

- web/src/components/Calendar.js
- web/src/pages/CalendarPage.js
- web/src/pages/RegistrationPage.js
Not all environments have access to the window object.
Our unit tests for instance don't have access.
This fixes errors being thrown in the tests
```
console.error node_modules/jsdom/lib/jsdom/virtual-console.js:29
Error: Not implemented: window.scrollTo
```
> Add a check for window before using scrollTo

- web/src/components/__tests__/Calendar.test.js
- web/src/locations/vancouver.js
- web/src/utils/__tests__/calendarDates.test.js
- web/src/utils/calendarDates.js
This adds a 'blocked' property to the location object to block off calendar days
export const test_location = {
recurring: {
...
},
blocked: '2018-10-02, 2018-10-03, 2018-11-21', // use CSV format => 2018-10-02, 2018-10-03, 2018-11-21
}
If the property exists the CSV string will be parsed and dates blocked on those values
<hr>
Adds utility method to parse a CSV string of dates
dateSetFromString takes a 'user entered' date string  i.e. 2018-10-17, 2018-11-06, 2018-11-07
and creates a new JavaScript set.
This will be used for checking if a given date is in the list set.has('2018-10-17')
> Adds ability to have blocked days on the calendar

- web/package.json
- web/src/pages/FourOhFourPage.js
- web/src/server.js
- web/yarn.lock
Sets up the server to handle locations via subdomain.
For local testing use vcap.me:3004 i.e. http://mtrl.vcap.me:3004
Valid subdomains have been whitelisted.
```
const domainOptions = { namespace: '', whitelist: ['van', 'cal', 'mtrl'] }
```
1. If a subdomain is found but is not on the list it will redirect.
2. If no subdomain is found for now it will default to Vancouver.
> Subdomains

- web/src/locations/index.js
- web/src/server.js
This PR contains a few fixes for problems we're seeing on the staging site to do with subdomains.
- if subdomain is `rescheduler-dev`, default to vancouver
- if location exists and is different from the location already set in `getGlobalLocation`, we should update the location
- otherwise the first location set on the server becomes the no-JS location for everyone else
- remove home page caching temporarily while we are troubleshooting this
> Hotfixes for subdomains

- web/src/server.js
Given our DNS setup this package seems to be not needed and is causing matching issues with the router.
Keeping the whitelist to check against.
> remove wildcard subdomain package

- web/src/components/__tests__/Calendar.test.js
This is a workaround for jsdom/jsdom#1422. This just prevents a bunch of
console.error output from cluttering the test results.
> Supress jsdom console.error output

- web/src/__tests__/WithProvider.test.js
Added some more tests to withProvider to verify that given inputs result in given outputs.
This was part of the work around adding global locations (which was closed: #388) but ultimately works independently of that.
Plus, we had some strange behaviour with these query params before so more tests === better.
> Add some extra checks to WithProvider

- web/src/components/FederalBanner.js
- web/src/components/Footer.js
- web/src/components/Language.js
- web/src/components/__tests__/FederalBanner.test.js
- web/src/components/__tests__/Footer.test.js
- web/src/components/__tests__/Language.test.js
- web/src/context.js
- web/src/pages/CalendarPage.js
- web/src/pages/LandingPage.js
Started working on this earlier as an offshoot of #388, but then left it for a while.
React context contains pretty much all of the session data we have throughout the app, but it's not always easy to get.
If all we need is the language string, wrapping another component in `Language`, and passing the language string as a render prop is quite a bit easier than doing a large object destructure every time.
Usage looks like:
```js
<Language
render={(language) => (<span>The language is {language}</span>) } 
/>
```
> Add Language component to application

- app.json
- web/README.md
- web/src/email/sendmail.js
- web/src/server.js
This update makes use of the existing RAZZLE_SITE_URL env variable.  We'll need to update that to allow the site to redirect to a "generic" not found and maybe error page as needed.
@pcraig3 to be discussed should we keep the "base domain" alive to host generic pages (no location etc... needed)?
> Use env var for site url / redirect

- web/cypress/integration/main/generic-not-found.spec.js
- web/src/components/Footer.js
- web/src/server.js
If redirecting from the server (i.e. no location found) we need to have a generic not found page.  This is needed to avoid people contacting an incorrect office.
Checks are based on a specific page name /not-found
Other 404 pages /some-page will be treated as a location not found page and still contain the contact link
**/not-found**
<hr>
**/some-missing-page**
> Remove contact link on generic not found page

- web/README.md
- web/src/cookies.js
- web/src/server.js
So this is a best-guess.
If we're running locally, we're probably on 3004.
If that's in the site URL, we want to stay on HTTP.
**Other option that occurred to me:**
Might be better to re-use the `RAZZLE_COOKIE_HTTP` var since that one is only for HTTP environments.
> Use http as redirect protocol if running locally

- web/src/email/sendmail.js
- web/src/locations/index.js
- web/src/server.js
In our middleware, we will throw an error if there is no location string or if there is no receiving email address shown.
On the landing page, if we hit an error, it would redirect to the error page.
Unfortunately, the error page would also encounter the same error.
This meant that we would end up with an infinite loop if we ran into any of these.
This commit generalises some of the code, and helps mitigate infinite error loops. **Line 100 is the operative one**: `if (req.path === '/error') return next()`
*Note: this doesn't get us out of the woods because we can still have the location string taking down the app if it's not there at all, but it helps.*
> Stop infinite loop for startup errors

- web/cypress/integration/main/force-redirect.spec.js
- web/src/server.js
When a user is visiting the website using the staging or live url + the base sub-domain we need to redirect to a proper location sub-domain.
Later we will 404 the use of the base sub-domain but this case needs to be handled for existing links.
**Testing manually :**
Use: http://rescheduler-dev.vcap.me:3004 & http://rescheduler.vcap.me:3004
> Enforce subdomain

- web/cypress/integration/main/force-redirect.spec.js
- web/src/server.js
After moving the app to use sub-domains we lost the ability to have branch deploys running on Heroku.
The update sets a default location (vancouver) if a "Heroku" url is detected in the form of https://ircc-development-pr-420
> Fix Heroku branch deploys

- web/cypress/integration/main/form-bela-params.spec.js
- web/cypress/integration/main/form.spec-fr.js
- web/cypress/integration/main/form.spec.js
- web/cypress/integration/main/full-run.js
- web/cypress/integration/main/validation-error-query-params.spec.js
The tests are firing multiple emails every time there is a PR.  This limits the emails sent per run down to a single test that does a full run with validation errors.
Ideally with less emails being sent if something is off we'll notice sooner.
@pcraig3 ultimately it would be nice to find something that would verify receipt to an inbox.  Looking to at least cut down on the noise for now.
> Limit emails sent by tests

- web/src/components/Calendar.js
This pauses and slows down the arrow animation.  With CSS animation there isn't 'proper' way to pause and animation.  Best practice seems to be to extend the length of the animation and create a 'resting' state for a given period of time.
> Add pause to animate arrow

- web/cypress/fixtures/user.json
- web/email_templates/applicant-plain.html
- web/email_templates/applicant-rich.html
- web/src/email/email-template.js
- web/src/pages/ReviewPage.js
With the addition of https://github.com/cds-snc/ircc-rescheduler/pull/438 the email templates need to handle either selected days or the availability explanation.  This updates handles the new scenarios and is backwards compatible with the existing setup.
To test locally run update the cypress user fixture to your email address and run "validation-error.spec" (Full Run-through including validation errors).  To test with an availability explanation add an explanation manually i.e. 
```
options.formValues.availabilityExplanation = "Hey this works!"
if (
typeof options.formValues.availabilityExplanation !== 'undefined' &&
options.formValues.availabilityExplanation !== ''
) {
renderAvailabilityExplanation(options)
} else {
renderSelectedDays(options)
}
...
``` 
Sample user email:
> Update email templates to handle availability explanation

- .circleci/config.yml
Since moving to containerized deploys instead of shipit deploys, we lost our sourcemap uploads to sentry.
This PR adds a step to circleci which will upload the sourcemaps after the container deploys.
Added a new environment variable called `SENTRY_AUTH_TOKEN` to circleci so that the uploads work.
Currently using _my_ auth token, so we can change that in future if needed.
> Upload sourcemaps from circleci after container deployment

- web/src/components/Summary.js
- web/src/components/__tests__/Summary.test.js
Our site is currently performing like this:
| TextArea Input | ReviewPage Output |
|----------------|-------------------|
|    ![screen shot 2018-09-14 at 18 04 52](https://user-images.githubusercontent.com/30609058/45577193-c0680a00-b848-11e8-8acc-b565db779660.png) | ![screen shot 2018-09-14 at 18 05 06](https://user-images.githubusercontent.com/30609058/45577191-bfcf7380-b848-11e8-8a37-0137db04970d.png) |
We want to be preserving the line breaks on the familyOption row of the Summary component
| TextArea Input | ReviewPage Output |
|----------------|-------------------|
|  ![screen shot 2018-09-14 at 18 04 52](https://user-images.githubusercontent.com/30609058/45577193-c0680a00-b848-11e8-8acc-b565db779660.png)  | ![screen shot 2018-09-14 at 18 05 …
> Preserved line breaks

- web/email_templates/applicant-plain.html
- web/email_templates/applicant-rich.html
- web/email_templates/staff-plain.html
- web/email_templates/staff-rich.html
- web/src/email/email-template.js
Previously, if your name was "Paul Craig" and your familyOption string was "Julia Craig, Kevin Craig" we would have:
- `Paul Craig Julia Craig, Kevin Craig`
Now we will have
- `Paul Craig, Julia Craig, Kevin Craig`
This doesn't solve every case, but I would assume it's an improvement in the vast majority of cases.
*Note: Since `options.formValues` is an object we keep in memory between function calls, we have to check that a comma and a space have not already been prepended.*
This closes #443
> Prepend a comma and space to familyOption string in emails

- web/src/server.js
- web/src/utils/serverUtils.js
For our manually triggered Raven errors (ie, `Raven.captureException` or `Raven.captureMessage`), Raven isn't capturing all the contextual data automatically, the way it does when it captures a `throw new Error` event.
What this means is that we have a lot of errors showing up in sentry because our tests trigger them, but we're not able to at-a-glance know when they're coming from our production application.
By setting a global context.extra, all exceptions and messages captured will have the following useful context:
- `tags`
- the url host name
- the subdomain
- the url path
- the RAZZLE_STAGE env var
- `extra`
- the release string
**Note: since the context is only getting set on server reloads, the req.path will not be up to date unless the error happens on the first page. I think this …
> Set global 'extra' context for raven

- web/src/components/Calendar.js
- web/src/components/Summary.js
When coming back from the review page this will give focus to the selected day box to make it eaier to remove days before moving back to the calendar.
> Give focus to selected day box

- web/src/components/Calendar.js
- web/src/components/MobileCancel.js
- web/src/components/__tests__/Calendar.test.js
Flagged by axe: ids should be unique on a page and we were using duplicates for the <title> element inside of the "Remove day" button svg.
Looked into writing a pa11y test for this, but it was not going to be straightforward, so just going to add the fix by itself.
> Generate unique id attributes for cancel button svg titles

- src/components/Layout.js
NODE_ENV is set to production in various places, but RAZZLE_STAGE is only set to production on our prod server.
We don't want GA views being logged from staging or ci, so this is a better check for that.
> Don't activate GA unless RAZZLE_STAGE is production

- src/email/email-template.js
- src/utils/__tests__/calendarDates.test.js
- src/utils/calendarDates.js
- src/withProvider.js
Respond by date is no longer in use to calculate when the user will receive a response by.
The new setup is coded into the templates based on the family option.
> Remove respond by date

- src/components/Calendar.js
- src/pages/CalendarPage.js
Tests have been outputting a nested field warning because the Calendar tests are not wrapped with the CalendarPage that contains the Form.
"Warning: Field must be used inside of a ReactFinalForm component"
This adds a new property to workaround the issue.
> Fix "Field must be used inside" warning

- src/components/PhaseBanner.js
Noticed something I'd missed from an old issue: #186 
Specifically:
> BETA tag width should be the same as the flag in FIP 
> The text to the right of the BETA tag should be aligned with "Govt. of Canada" in the FIP above
This is a tiny update, just changes the width on the beta banner. Doesn't stay the same size as the flag on 400% zoom but on most screens it's good.
| old | new |
|-----|-----|
| flag is not aligned with beta tag | flag _is_ aligned with beta tag |
|  <img width="1502" alt="screen shot 2018-10-01 at 4 31 05 pm" src="https://user-images.githubusercontent.com/2454380/46314857-b14bc080-c599-11e8-9448-6c953b355a2b.png">   |  <img width="1502" alt="screen shot 2018-10-01 at 4 31 07 pm" src="https://user-images.githubusercontent.com/2454380/46314858-b27ced80-c599-11e8-9f26-69fe …
> Make Beta tag the same width as FIP flag

- src/components/Calendar.js
Previously, [our yellow focus ring wasn't high-enough contrast against the light green background](https://contrast-ratio.com/#rgb%28255%2C%20191%2C%2071%29-on-rgb%28185%2C%20218%2C%20199%29).
This one was tricky because we have 3 possible colours:
- a light green background when a day is not selected: ```#B9DAC7```
- a medium green background when a day is hovered: ```#70B48F```
- a darker green background when a day is selected: ```#1E874D```
Tested a few combos using http://jxnblk.com/colorable/demos/matrix/ and found that dark colours work fine. So the new focus ring for the days is black: ```#000000```.
Then changed the focus ring for disabled days to grey+dashed to visually de-emphasize it.
| …
> Update calendar date focus colours

- src/index.js
This was originally removed because it was needed for Heroku.
However, I suspect that our container deployments need it as well, so I am adding it back in.
> Add back in PORT configuration code

- src/components/Contact.js
- src/components/__tests__/Contact.test.js
Our root domain has no location set, so we don't have contact information to show users.
Right now, it will say `Phone —` but then not have a phone number.
Instead, we should omit the Contact output entirely if there is no contact info.
|  when there is a location ('vancouver' in the URL string), there is a phone number.  |  When there is *no* location, there is no phone number to call.   |
|  <img width="1474" alt="screen shot 2018-12-20 at 2 39 35 pm" src="https://user-images.githubusercontent.com/2454380/50307032-3c37ab00-0465-11e9-9175-78a0c37dade7.png">  |   <img width="1474" alt="screen shot 2018-12-20 at 2 39 42 pm" src="https://user-images.githubusercontent.com/2454380/50307036-3cd04180-0465-11e9-9265-a773ed6ec14c.png">  |
This PR removes the …
> Don't show "Phone -" on 500 page if no location

- src/components/FederalBanner.js
- src/components/Footer.js
- src/components/Layout.js
- src/components/PageHeader.js
- src/styles.js
After upgrading to emotion 10, our horizontal padding media queries broke for the main content but not for other parts of the app (for example, the header and footer were fine). This meant that on a phone, the main content would be pushed into the middle: you would have to scroll for longer, and in a few places some words were getting cut off.
So I've collected all the horizontal padding rules together and applied them uniformly.
Now they will all work or they will all break as a team.
| main content is not lined up with header  | main content is flush with header  |
| <img width="512" alt="screen shot 2018-12-24 at 12 49 17 pm" src="https://user-images.githubusercontent.com/2454380/50404816-790fe480-077a-11e9-8f00-9cde72649270.png">  | <img …
> Fix horizontal padding throughout the app

- src/server.js
- src/utils/serverUtils.js
Since the email that we want to send the request to will vary location by location, it is possible we might get into a position where we try to send an email but don't have one configured.
However, the logic needed to do this check has become increasingly cumbersome. For example,
- we want to check if we are in prod or staging
- if staging, we want to check for the 'test' email env var
- if prod, we want to check for the location being set
- and now we would also have to check if we are at the root domain or not
We could either keep piling logic into our `getReceivingEmail` method, OR, accepting the risk, we could remove the check we do on every request.
This means that a potential missing email would only be discovered when someone is about to submit a request rather than on app startup …
> Remove "ensure receiving email" logic on every request

- package.json
- src/components/FocusedH1.js
- yarn.lock
This is a patch update that bumps Razzle in response to a Snyk vulnerability.
I've also added prop-types to `FocusedH1` because locally my linter started complaining.
> Update Razzle to fix nested package vulnerability

- src/pages/__tests__/NoJS-familyErrorCheck.test.js
- src/pages/__tests__/puppeteer-config.js
These family check tests are pretty frequently causing errors in our deploy process, even through they run fine locally.
I've looked it up and there are a few issues on github where people add this extra argument when it runs on CI. Also I've split out the two family tests from each other. 
Maybe one of these will resolve our issue.
There's nothing wrong with the test, so I don't want to turn it off.
> Add another sandbox flag to puppeteer

- src/pages/__tests__/NoJS-familyErrorCheck.test.js
- src/utils/analytics.js
Now that
- we are using POST parameters to pass data between pages
- we have anonymized IP addresses that Google Analytics collects
we should be a-okay to turn GA back on.
(Note, this isn't being initialized on our staging environment, so we will only be able to test these changes locally or on the production version of the app.)
>  Enable Google Analytics

- .circleci/config.yml
- README.md
Something about our setup keeps failing these specific tests on CircleCI, so PR builds and releases keep failing.
There have been a couple attempts to ameliorate this in the past but these tests continue to fail intermittently.
Biting the bullet and removing them from CircleCI.
They can still be run locally with `yarn test:full`
> Skip puppeteer tests on CI

- cypress/integration/main/form-bela-params.spec.js
- cypress/integration/main/form-family.spec.js
- cypress/integration/main/form.spec-fr.js
- cypress/integration/main/form.spec.js
- cypress/integration/main/generic-not-found.spec.js
- cypress/integration/main/validation-error.spec.js
- src/email/sendmail.js
This pull request sets us up for future deployments.
We need to be able to change the dates that show up on the calendar, and we also want to add a warning banner to the site, but before we do that, we need the tests to pass on CI so that we can deploy the container.
Since we're no longer adding the credentials to the container, the
tests won't be able to send the email, which means they will fail.
This is not an elegant solution but it is an expedient one.
This is the code from #532. 
From @dsamojlenko 
> Updated infrastructure removes the need for the app to have access to AWS credentials in the environment. Once it's deployed, this change can be merged.
> Less tests 😭

- src/email/sendmail.js
*Don't merge until new infrastructure is deployed.*
Updated infrastructure removes the need for the app to have access to AWS credentials in the environment.  Once it's deployed, this change can be merged.
> Removed dependency on aws credentials

- src/server.js
- src/utils/serverUtils.js
- test/server.test.js
Updated default headers with:
- a [Content Security Policy](https://helmetjs.github.io/docs/csp/)
- an [HSTS](https://helmetjs.github.io/docs/hsts/) header
And removed the `noCache` header as I don't think we need it.
Read more here:
- https://expressjs.com/en/advanced/best-practice-security.html#use-helmet
- https://helmetjs.github.io/docs/
> Add Content Security Policy and HSTS default headers

- Dockerfile
Since `alpine` is pretty general, we want to at least make sure we're on a long-term support version of node.
Node release numbers can be found here: https://nodejs.org/en/download/releases/
Tags for the official node Docker image can be found here: https://hub.docker.com/_/node/
> Build container latest long-term support node version
