cds-snc/ircc-rescheduler

.babelrc
package.json
src/AlphaBanner.js
src/FederalBanner.js
src/Footer.js
src/HomePage.js
src/server.js
src/styles.js
yarn.lock

This PR consists of:
- Migrating the Alpha/Federal Banners and Footer components from nrcan project into the new IRCC project
- Importing these components into HomePage before implementing to others

Top banners

---

src/AvailabilityPage.js
src/CalendarPage.js
src/ConfirmationPage.js
src/HomePage.js

Same as with the proof of concept, I've added some HTML we can break out into components later (or even replace altogether because some of these components we already have prebuilt).
It's mostly semantic HTML but it looks terrible at the moment.

Add placeholder markup

---

.circleci/config.yml

Once this is in, we will have continuous integration (automatically running tests) and continuous deployment (automatically deploying the app) to https://ircc-poc.azurewebsites.net/

Add deployment configuration

---

package.json
src/AlphaBanner.js
src/Document.js
src/Footer.js
src/GraphQLPage.js
src/PageHeader.js
src/__tests__/After.test.js
src/__tests__/FederalBanner.test.js
src/index.js
src/routes.js
src/server.js
src/styles.js
yarn.lock

Let's get linting going on

---

src/AvailabilityPage.js
src/CalendarPage.js
src/ConfirmationPage.js
src/Footer.js
src/HomePage.js
src/__tests__/AlphaBanner.test.js
src/__tests__/Footer.test.js
src/styles.js
test/server.test.js

This PR consists of:
- Creating tests for new components
- Applying styling to all other pages

Page-wide styling + tests

---

.circleci/config.yml
Dockerfile

We've had some linting errors slip through, but we shan't anymore!

Add linting to our circleci config

---

src/Calendar.js

Disable every day other than Tues/Fri

---

src/CalendarPage.js
src/ConfirmationPage.js
src/HomePage.js
src/styles.js

Styling the HomePage and swapping content to match Eman's feedback

Content Change HomePage

---

src/CalendarPage.js
src/ConfirmationPage.js
src/HomePage.js
src/styles.js
test/server.test.js

This PR consists of:
- Minor Styling
- Matching content to new wireframes
- Minor change from UCI number -> Paper file number

Content Update

---

src/HomePage.js
src/forms/TextInput.js

text area is now a seperate module from text input. The TextAreaAdapter is set to accept an input var which contains properties like name,id, etc..

Separate the text input from text area

---

src/Calendar.js
src/CalendarPage.js
src/ConfirmationPage.js
src/Footer.js
src/HomePage.js
src/forms/MultipleChoice.js
src/styles.js

- Configures the calendar to only show June 2018 and July 2018 
- Adds a grey background to the content area of the app, matching the wireframes

CSS fixes and calendar update

---

.circleci/config.yml

This properly sets the directory in the deploy job.

Fix for deploy job

---

.circleci/config.yml

As advertised. Build and push api container to docker hub if the tests pass.

Update circleci config to deploy api

---

api/README.md
api/index.js
api/package.json
api/src/schema.js
api/src/types/MailResponse.js
api/test/api.test.js
api/yarn.lock

This is currently done via AWS SES.

Get basic email sending going

---

api/package.json
api/yarn.lock

Cleanup API project deps

---

web/src/ConfirmationPage.js
web/yarn.lock

This PR consists of:
- using the contentClass to add vertical spacing to the H1 on the confirmation page

vertical spacing added to H1 on confirmation page

---

api/src/messages.js
api/src/schema.js
api/src/types/RescheduleForm.js
api/test/api.test.js

This adds an input type that lines up with the fields of the rescheduling form.

Add input type representing the rescheduling form

---

web/src/Layout.js
web/src/LinkStateDisplay.js
web/src/RegistrationPage.js
web/src/__tests__/RegistrationPage.test.js
web/src/queries.js
web/src/utils/createApolloClient.js

Pretty much what it says on the tin.
Also removes an incorrect aria attribute.

Our form field id is now asking for a paperFileNumber instead of a uciNumber

---

web/package.json
web/yarn.lock

This commit updates Razzle and After.js

Update to After and Razzle

---

web/src/Document.js
web/src/LandingPage.js
web/src/Layout.js

-Fix html error regarding a style within a span - also add the ircc website
-remove main role
-add title fix but still need to add translation
- move href class to the <a> tag

Html validation fixes - fixed 4 of them 

---

web/src/forms/Button.js

Simply export the component created by styled.button.

Simplify Button component

---

web/src/ReviewPage.js
web/src/queries.js
web/src/utils/createApolloClient.js

Submits the form data to the API.

Submit form to graphql endpoint

---

api/src/messages.js
api/src/types/RescheduleForm.js

Add translations for RescheduleForm input type

---

web/src/components/Calendar.js
web/src/components/ErrorMessage.js
web/src/components/Reminder.js
web/src/components/__tests__/ErrorMessage.test.js
web/src/pages/CalendarPage.js
web/src/pages/RegistrationPage.js
web/src/styles.js

- Implementing the ErrorList component on the Calendar Page
- OnSubmit should send the page focus to this ErrorList should any information be faulty or missing
- This list will then display anchor links to the fields that are missing. In this case there is only one, the calendar dates selected.
|  ![calerrorlist-before](https://user-images.githubusercontent.com/30609058/41065387-7b866296-69ac-11e8-8f19-bcb8875c9994.gif) | ![calerrorlist](https://user-images.githubusercontent.com/30609058/41065408-879865de-69ac-11e8-9e60-46ad25169dca.gif) |
- ErrorList Focus styling changes on RegistrationPage.js
- The Focus styling on the list now matches the yellow from other pages.
- A focusRing style was made in styles.js as well
| Before | …

Calendar Error List + Focus Styling

---

web/.gitignore
web/locale/_build/src/components/Calendar.json
web/locale/_build/src/components/Layout.json
web/locale/_build/src/components/Summary.json
web/locale/_build/src/pages/CalendarPage.json
web/locale/_build/src/pages/ErrorPage.json
web/locale/_build/src/pages/RegistrationPage.json
web/locale/en/messages.json
web/locale/fr/messages.json
web/package.json
web/src/components/ErrorMessage.js
web/src/components/__tests__/ErrorMessage.test.js
web/yarn.lock

**Note: This shouldn't go in until after #138 makes it in**
This pull request cleans up a few things rather than adding anything interesting.
- updates our translations again so that our app is a bit more polished-looking 
- adds back `messages.js`, this is a small change that will resolve issue #76 
- render our errors in ErrorList in an HTML list. no visual changes
- updates a dependency to cut down on warnings when we build our app

Smallish cleanup-type changes

---

web/src/components/Reminder.js
web/src/pages/LandingPage.js

- Changing the Reminder.js component's styling so that the bounding circle of the exclamation icon is aligned with the text
|    ![41064899-e2cc6ab0-69aa-11e8-9d7f-9b8adf624fb4](https://user-images.githubusercontent.com/30609058/41364706-6aa847d8-6f05-11e8-89d5-efa34ae2be96.jpg) |  ![screen shot 2018-06-13 at 12 30 26](https://user-images.githubusercontent.com/30609058/41364760-94e2e99a-6f05-11e8-8a65-4d8d9fd2756b.png)|

Warning box

---

web/src/pages/CalendarPage.js
web/src/pages/RegistrationPage.js
web/src/pages/ReviewPage.js

This PR 
- adds a Cancel button to the form page
- changes the copy to "Cancel request" from "Cancel" as noted in design review
This PR does not address functionality changes for the Cancel button captured in other issues

Copyediting Pass [Bulk commits]

---

web/src/components/ErrorMessage.js
web/src/components/__tests__/ErrorMessage.test.js
web/src/pages/CalendarPage.js
web/src/pages/LandingPage.js
web/src/pages/RegistrationPage.js
web/src/pages/ReviewPage.js
web/test/server.test.js

This PR makes several small updates to copy across the Landing page, Review page, Calendar page, and error messaging.
- header on the front page:
- ordering of fields in error message + adding "address" to "Email" in that deep link list
- switching to correct dates for Vancouver
- "Review" -> "Review request" to match "Send request" on the next page
- removing "before you send it" from the title on the revie wpage

[Polish Pass] Copy updates throughout

---

api/index.js
web/src/index.js

Small update output server port #'s to console.  Helpful for someone new to the project to know where to view app / api.

log server port #'s to console

---

web/src/components/Chevron.js
web/src/components/Layout.js
web/src/pages/CalendarPage.js
web/src/pages/CancelPage.js
web/src/pages/ErrorPage.js
web/src/pages/FourOhFourPage.js
web/src/pages/RegistrationPage.js
web/src/pages/ReviewPage.js
web/src/pages/__tests__/CancelPage.test.js
web/src/pages/__tests__/ErrorPage.test.js
web/src/routes.js

cancel page

---

web/src/pages/NoJSCalendarPage.js
web/src/routes.js

- Creating a template (JSX + CSS) as a base for the noJS Calendar

NoJS Calendar Base

---

web/src/components/Submission.js
web/src/pages/ReviewPage.js

This prevents people from pressing "send request" multiple times.
|   ![button-1](https://user-images.githubusercontent.com/2454380/41921297-8cf49492-7930-11e8-8aa3-84c0c5ab61d9.gif)  |  ![button-2](https://user-images.githubusercontent.com/2454380/41921481-f5373b54-7930-11e8-8871-860b09a57392.gif)    |

Submit button is disabled while waiting for API response

---

api/src/email.js

Our file has a capital "W". (oops)

Fix filepath for Wordmark

---

web/src/cookies.js

There are a few cookie improvements in here:
- cookies set on the server or the client both have the same expiry date of 1 week
- previously the expiration date was static, which meant it
wasn't relative to the current time. Now it is
- cookies that can't be read are overwritten
- before, an error when trying to parse cookies would stop you from setting new ones
- all cookies are encrypted

Longer-lasting, overwriteable cookies

---

web/src/components/CancelButton.js
web/src/pages/CalendarPage.js
web/src/pages/RegistrationPage.js
web/src/pages/ReviewPage.js
web/src/server.js

Adds clear functionality to clear user data (cookies) when they press the cancel button. 
Prior functionality took the user to the cancel page but didn't clear the user data.

Cancel clear

---

web/src/components/CalendarNoJS.js
web/src/components/ErrorMessage.js
web/src/pages/CalendarPage.js

- Adds calendar redirect to the review page once dates have been filled in
- Refills checkboxes if coming back from the review page
- Refactors logic to properly display days in columns by months

No js calendar - redirect

---

api/src/schema.js
api/test/i18n.test.js
web/src/server.js

Add new mutation for testing server-side API call

---

web/src/components/ErrorMessage.js
web/src/components/Footer.js
web/src/components/Layout.js
web/src/components/PageHeader.js
web/src/components/forms/Button.js
web/src/pages/LandingPage.js
web/src/styles.js

- reorder footer links
- a + a:visited colour
- change site background to white
This is supposed to be the same code as https://github.com/cds-snc/ircc-rescheduler/pull/209/files, so look there for the screenshots etc.

Site-wide design edits

---

web/src/pages/ReviewPage.js
web/src/server.js
web/src/utils/createApolloClient.js

This is for our No-JS flow.
When we press the "submit" button on the review page, then we make a call from the server.

Make a GraphQL post from the server

---

api/src/server.js
web/package.json
web/src/server.js
web/test/server.test.js
web/yarn.lock

-Included the helmet api, the one we have is react based
-added unit tests to make sure the headers stay there
-added frame guarding, cache control, xss protection, and anti-mime sniffing. 
-disable graphiql interface when in production environment

Add http headers in compliance with security checks

---

web/src/pages/ReviewPage.js

Fixup button text I had in for testing.

Fix text "Send request" for no JS page

---

web/src/server.js
web/src/utils/createApolloClient.js

Pass in absolute uri for server GraphQL call

---

web/src/server.js

Forgot trailing graphql

---

web/src/components/Contact.js
web/src/components/__tests__/Contact.test.js

Contact email should be real email

---

web/package.json
web/src/pages/RegistrationPage.js
web/yarn.lock

|   ![pr errorjumping](https://user-images.githubusercontent.com/30609058/42710360-bb18861a-86b1-11e8-9043-810f04a5c0e2.gif)     |  ![pr errorjumping-after](https://user-images.githubusercontent.com/30609058/42710361-bb29888e-86b1-11e8-9cee-75c1008cab23.gif)     |
- Fixing the Error jumping bug found on the Registration Page while in the safari browser.
| ![pr errorlist-before](https://user-images.githubusercontent.com/30609058/42710382-d2a93d10-86b1-11e8-96af-2acafaab68b5.gif) | ![pr errorlist-after](https://user-images.githubusercontent.com/30609058/42710383-d2b9bac8-86b1-11e8-8873-dd1802c29082.gif) |
- Fixing the broken anchor links in the ErrorList while in the safari browser.

Error list fix

---

web/src/pages/CalendarPage.js
web/src/pages/RegistrationPage.js

Same as we did on the RegistrationPage.
Check out #250 for more context.

Add HashLink and window.scrollTo to CalendarPage

---

shipitfile.js

Adding the details for the new dev server in AWS space

add new dev server details

---

package.json
shipitfile.js
web/src/email/sendmail.js

This is as-documented in the Rezzle docs.
All user-created environment variables must be prefixed with `RAZZLE_`

Prefix all environment variables with RAZZLE_

---

web/src/components/Summary.js

Update to restore HashLink functionality to the review change links.

Fix hash links that got dropped with merge conflict

---

web/src/components/Calendar.js
web/src/components/ErrorMessage.js
web/src/components/Summary.js
web/src/components/__tests__/Calendar.test.js
web/src/pages/CalendarPage.js
web/src/styles.js

|   ![screen shot 2018-07-20 at 11 21 28](https://user-images.githubusercontent.com/30609058/43010689-1e8544ec-8c0f-11e8-94c7-0006a073e8bc.png) |   ![screen shot 2018-07-20 at 11 20 32](https://user-images.githubusercontent.com/30609058/43010688-1e6661da-8c0f-11e8-8fd5-f6717c3eaa44.png)   |

Removed breaking to single column layout for summary info on Mobile

---

web/src/components/Footer.js
web/src/components/__tests__/Footer.test.js

Add IRCC email address to footer contact link

---

web/README.md

Add new ENV var to README

---

shipitfile.js
web/cypress.json
web/cypress/integration/main/cal.spec.js
web/package.json

Once this is in, we should be able to upload source maps to sentry when our app is deployed.

Upload source maps on deploy

---

shipitfile.js
web/package.json
web/src/Document.js
web/src/server.js
web/src/utils/gitHash.js

Accidentally added a space to the build path

---

shipitfile.js
web/package.json

This has been tested ✨ on the server ✨ so it will work for sure. 😎

Stop passing env vars around package.json file

---

web/src/components/Calendar.js
web/src/components/LanguageSwitcher.js
web/src/pages/CalendarPage.js
web/src/pages/RegistrationPage.js
web/src/utils/analytics.js

Adds event tracking for the Calendar and Registation pages
1. Will log Calendar Submit event for errors. The event will be submitted with a label containing the number of days selected by the user.
2. Will send a Registration Submit Event with a label matching the field errors i.e.
Error(s): fullName, Email..., paperFileNumber, Reason

Google Analytics tracking for form errors

---

app.js
web/app.js

- Adds all the env vars we need to run the app
- Adds a buildpack that should let us deploy from a subdirectory
Note: added two files since I'm not sure which one heroku will pick up.

Add heroku config files

---

web/cypress/integration/main/cal-introtext.spec.js.js

Quick fix to get test passing again as the sentance was updated.

Calendar intro text test fix

---

docs/upgrade.md

Adds vulnerability process to the docs in response to https://github.com/cds-snc/ircc-rescheduler/issues/349

Outline vulnerability process

---

web/src/Document.js

hotfix no cache bundle

---

web/cypress/integration/main/subdomain.spec.js

Adds some simple tests check if the correct location is loading on the cancel page.

Add tests to check email for location

---

web/README.md

Outline the steps for adding translations to the app.

Translations readme

---

README.md

Adds a link to the project setup Readme

Add project setup link

---

web/email_templates/staff-plain.html
web/email_templates/staff-rich.html
web/src/pages/RegistrationPage.js
web/src/pages/__tests__/NoJS-family.test.js
web/src/pages/__tests__/NoJS-familyErrorCheck.test.js
web/src/pages/__tests__/NoJS.test.js

Users are unsure if they should be putting their own email address or a family member's email address.
This moves the email field up.

Move email field up

---

web/src/components/LanguageSwitcher.js

To confirm how the text will read on EN vs FR
https://github.com/cds-snc/ircc-rescheduler/issues/447

WIP - Announce language toggle

---

web/src/components/Calendar.js
web/src/components/MobileCancel.js
web/src/components/__tests__/Calendar.test.js

@pcraig3 thoughts on best way to test this?  Should we have it on the button and the image?

Add full date 'x' icon (remove selected day)

---

web/src/components/CalendarH1.js

Considered making this just a function but going to leave as a Component to allow for easier future changes.
Confirming copy.

Update calendar heading copy

---

web/src/pages/CalendarPage.js
web/src/pages/CalendarPageNoJS.js
web/src/pages/calendar/CalBottom.js
web/src/pages/calendar/CalHeader.js
web/src/utils/calendarDates.js

This splits out the Calendar page into more manageable pieces.
Breaks out the Header, Footer and NoJS calendar page.

Refactor calendar page

---

web/src/pages/CalendarPage.js
web/src/pages/calendar/CalBottom.js

If a user selects the not available for dates checkbox this hides the "stay available warning".

Toggle stay available warning

---

docs/location-setup.md

This update shows an example of how to update available days.
Note: This is an example was requested for the handover docs.

Document how to update available days

---

web/src/components/Calendar.js
web/src/styles.js

Updates for https://github.com/cds-snc/ircc-rescheduler/issues/446
**Default:**
|-----|-----|
| ![before](https://user-images.githubusercontent.com/62242/46040895-8536c800-c0df-11e8-8c32-68dcb780b0fa.gif)  |  ![after](https://user-images.githubusercontent.com/62242/46040905-8bc53f80-c0df-11e8-8717-589075842468.gif)  |
**Inverted:**
|-----|-----|
|  ![before-inverted](https://user-images.githubusercontent.com/62242/46040965-adbec200-c0df-11e8-83eb-77f99f948987.gif) |  ![after-inverted](https://user-images.githubusercontent.com/62242/46040974-b1524900-c0df-11e8-86e2-597cb65d7180.gif) |

Cal contrast updates

---

web/src/components/Calendar.js
web/src/pages/CalendarPage.js

~Release the kracken 🦑~
whoops, I meant release the unavailability flow.

Remove FeatureFlags! Unavailability flow is go.

---

README.md

Add content to describe the service and it's purpose

Describe the service

---

package.json
yarn.lock

This adds a pre-push git hook to run `yarn lint && yarn test` prior to code being pushed to this repo.
No more lint commits after pushing to the repo :)

Add husky pre-push command to lint

---

README.md
docs/error-tracking.md
docs/feature-flags.md
docs/location-setup.md
docs/translations.md
docs/upgrade.md
package.json

Added `Technical overview` section, table of contents, and emojis.
Probably going to clean this up some more, but I've been working on this for while and want to have it open as a PR.

Update README before handoff

---

src/utils/analytics.js

This PR removes the Google analytics calls.  The functions have been left in place but the tracking calls are removed.

Disable GA

---

.cloudformation/production/main.yml

just bringing the production cloudformation templates up to date with changes made on staging

Update production cf config
